### PR TITLE
Added batch sink

### PR DESCRIPTION
**Pull request by Kheldar**
Also rebased from hw/master

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
Instead of rebasing, could you just take it discarding the packetloop one completely? We never use packetloop one and I don't know why there have diverged

**Comment by AlexeyRaga** [comment]
👍

**Comment by Kheldar** [comment]
Aren't we supposed to push open-source stuff from the Packetloop org?

**Comment by Kheldar** [comment]
Also, I don't have permissions to merge this.

**Comment by AlexeyRaga** [comment]
I meant to pull hw/master into packetloop/master first, then merge your changes in. The diff in this case will be just your changes and not everything that hw brings.

Although I guess the result would be the same, so please merge :)

**Comment by Kheldar** [comment]
I tried that - again, no permissions.

**Pull request merged**
